        <tr>
          <td width="10" height="30"><img src="images/empty.gif" height="30" width="1"></td>
          <td valign="bottom" align="right" colspan="2">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td valign="bottom"><i><font color="#BCBCBC"><b></b></font></i></td>
                <td align="right">
                  <table width="360" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td width="24"><a href="mailbox.php?mbox_id=INBOX"><img src="images/bt_email.gif" width="24" height="24" border="0"></a></td>
                      <td nowrap>&nbsp;<a href="mailbox.php?mbox_id=INBOX" class="style8"><? echo $text20; ?></a>&nbsp;&nbsp;</td>
                      <td width="27"><a href="notebook.php"><img src="images/bt_notebook.gif" width="24" height="24" border="0"></a></td>
                      <td nowrap>&nbsp;<a href="notebook.php" class="style8"><? echo $text21; ?></a>&nbsp;&nbsp;</td>
                      <td width="24"><a href="addressbook.php"><img src="images/bt_addressbook.gif" width="24" height="24" border="0"></a></td>
                      <td nowrap>&nbsp;<a href="addressbook.php" class="style8"><? echo $text22; ?></a>&nbsp;&nbsp;</td>
                      <td width="24"><a href="favorites.php"><img src="images/bt_favorites.gif" width="24" height="23" border="0"></a></td>
                      <td nowrap>&nbsp;<a href="favorites.php" class="style8"><? echo $text23; ?></a>&nbsp;&nbsp;</td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
          </td>
        </tr>
