<?
/*
   File name         : dutch.inc
   Version           : 1.1.1
   Last Modified By  : Frederik Denkens
   e-mail            : fdenkens@ilibris.be
   Purpose           : Dutch localization support for Postaci Webmail.
   Last modified     : 03 Oct 2000
*/

$lang_id = 4;
$lang = 'Dutch';
$charset = 'iso-8859-1';

/*************************************************/
/*                 User Panel                    */
/*************************************************/

$text1 = 'Gelieve uw gebruikersnaam en paswoord in te vullen';
$text2 = 'Gebruikersnaam';
$text3 = 'Paswoord';
$text4 = 'Aanmelden';
$text5 = 'Foutieve gebruikersnaam of onjuist paswoord. Gelieve nogmaals te proberen.';
$text6 = 'INBOX';
$text7 = 'Verstuurd';
$text8 = 'Klad';
$text9 = 'Er is een onbepaalde fout opgetreden!';
$text10 = 'selecteer alles';
$text11 = 'deselecteer alles';
$text12 = 'Van';
$text13 = 'Onderwerp';
$text14 = 'Datum';
$text15 = 'Grootte';
$text16 = 'Verplaats de geselecteerde items naar';
$text17 = '  ';
$text18 = 'OK';
$text19 = 'Totaal aantal berichten';
$text20 = 'e-mail';
$text21 = 'Notas';
$text22 = 'Adresboek';
$text23 = 'Favorieten';
$text24 = 'Geen berichten in deze map';
$text25 = 'Nieuw bericht';
$text26 = 'Controleer op nieuwe post';
$text27 = 'Mappen';
$text28 = 'Instellingen';
$text29 = 'Stoppen';
$text30 = 'Vorig bericht';
$text31 = 'Volgend bericht';
$text32 = 'Naar';
$text33 = 'Bestanden';
$text34 = 'Beantwoord bericht';
$text35 = 'Stuur bericht door';
$text36 = 'Bewaar bericht';
$text37 = 'Druk bericht af';
$text38 = 'Steek dit bericht in map';
$text39 = 'Bericht nr';
$text40 = 'Geen onderwerp';
$text41 = 'Voeg bestand toe';
$text42 = 'Begin opnieuw';
$text43 = 'Verstuur bericht';
$text44 = 'Voeg toe aan lijst';
$text45 = 'Toegevoegde bestanden';
$text46 = 'Verwijder bestand';
$text47 = 'Ga terug';
$text48 = 'Maak vuilbak leeg';
$text49 = 'Oorspronkelijk bericht';
$text50 = 'Mapnaam';
$text51 = 'Verwijder map';
$text52 = 'Hernoem map';
$text53 = "OK";
$text54 = "Maak nieuwe map";
$text55 = "Nieuwe map naam";
$text56 = "Onderwerp";
$text57 = "Verwijder";
$text58 = "U hebt geen notas";
$text59 = "Totaal aantal notas";
$text60 = "Voeg nota toe";
$text61 = "Naam";
$text62 = "Telefoon";
$text63 = "U hebt geen contactpersonen";
$text64 = "Voeg een contactpersoon toe";
$text65 = "Toevoegen";
$text66 = "Notas";
$text67 = "Bewaren";
$text68 = "Website titel";
$text69 = "Website adres (URL)";
$text70 = "U hebt geen favorieten";
$text71 = "Voeg een site toe";
$text72 = "ERROR: Please edit global.inc to select the database type";
$text73 = "ERROR: Invalid database selection. Valid values : msql, mysql, postgresql, sybase, mssql";
$text74 = "ERROR: Invalid language selection. Valid values : nederlands, turkce, english";
$text75 = "ERROR: Can not connect to database. Check includes/global.inc for database settings.";
$text76 = "Meer over Postaci";
$text77 = "Auteurs";
$text78 = "Gesteund door";
$text79 = "Deze software gebruikt cookies. Gelieve cookies aan te schakelen in uw browser, of na te kijken of U niet achter een firewall/proxy zit die deze cookies verwijdert. De cookie bevat enkel numerieke gegevens, en zeker geen gevoelige gegevens.";
$text80 = "ERROR: You have an error in includes/global.inc : default_protocol setting. Correct the mistake and try again";
$text81 = "Spam Control";
$text82 = "Welkom bij Postaci";
$text83 = "Blokkeer afzender(s)";
$text84 = "iLibris.Net Webmail maakt gebruik van de uitstekende Open Source Webmail Interface Postaci. Meer informatie hierover kan U vinden op <a href='http://www.gnu.org' target='newwindow'>gnu.org</a>.";
$text85 = "Verwijder bericht";
$text86 = "Voeg toe aan adressenlijst";
$text87 = "Voeg toe aan spam lijst";
$text88 = "Bericht zonder inhoud";
$text89 = "De postbus die U wil bestaat niet. Gelieve nogmaals te proberen. Moest het niet lukken, gelieve contact op te nemen met de beheerder.";
$text90 = "U bent over de maximale gegevenshoeveelheid gegaan 2MB) of een andere fout heeft zich voorgedaan.";
$text91 = "Problemen met het versturen van het bericht. Gelieve contact op te nemen met de beheerder.";
$text92 = "Fout  : Er bestaat reeds een map met dezelfde naam of de postbus is niet leeg.";
$text93 = "Fout  : De naam voor de map moet ingevuld zijn!!";
$text94 = "Fout  : Map is niet leeg.";
$text95 = "Fout  : Er bestaat reeds een map met defzelfde naam";
$text96 = "De gebruiker werd succesvol toegevoegd aan het adresboek";
$text97 = "Spammer e-mail";
$text98 = "Datum toegevoegd aan lijst";
$text99 = "Niemand in de lijst";
$text100 = "Uw naam en voornaam";
$text101 = "Uw handtekening";
$text102 = "Ongeldig e-mailadres. Probeer opnieuw.";
$text103 = "Schone E-mail";
$text104 = "Vertoning";
$text105 = "berichten per pagina";
$text106 = "Klik op een adres om aan het geselecteerde gebied toe te voegen.";
$text107 = "Laat";
$text108 = "Toe daar is niet te controleren om het even wat.";
$text109 = "Spel Controle";
$text110 = "Oorspronkelijke Tekst (potentiële fouten in <b>vette letters</b>):";
$text111 = "Correcties:";
$text112 = "Verbeter";
$text113 = "Terugstellen";
$text114 = "Voortzetten";
$text115 = "Geen fouten.";
$text116 = "Boek van het Adres van de Vooruitzichten van de invoer was het Uitdrukkelijke (de Komma scheidde het Formaat van Waarden) de Invoer van het Boek van";
$text117 = "Adres Succesvol!";
$text118 = "De Invoer van het Boek van het adres was niet Succesvol!";
$text119 = "Instructies";
$text120 = "De Invoer!";



/*************************************************/
/*                  Admin Panel                  */
/*************************************************/



?>


