<?
/*
   File name         : spanish.inc
   Version           : 1.1.1
   Last Modified By  : Roberto Garcia
   e-mail            : webmaster@gsmspain.com
   Purpose           : Spanish localization support for Postaci Webmail.
   Last modified     : 07 Nov 2000
*/

$lang_id = 9;
$lang = 'Spanish';
$charset = 'iso-8859-1';
$spell_language = "es";

/*************************************************/
/*                 User Panel                    */
/*************************************************/

$text1 = 'Por favor, Introduce tu usuario y clave';
$text2 = 'Nombre de Usario';
$text3 = 'Clave';
$text4 = 'Conectar';
$text5 = 'Usuario o Clave incorrectos, por favor intentalo de nuevo';
$text6 = 'Entrada';
$text7 = 'Enviados';
$text8 = 'Borradores';
$text9 = 'Error desconocido!';
$text10 = 'Marcar todo';
$text11 = 'Desmarcar todo';
$text12 = 'De';
$text13 = 'Titulo';
$text14 = 'Fecha';
$text15 = 'Tamaño';
$text16 = 'Mover mensajes marcados a';
$text17 = '  ';
$text18 = 'OK';
$text19 = 'Total mensajes';
$text20 = 'e-mail';
$text21 = 'notas';
$text22 = 'agenda';
$text23 = 'favoritos';
$text24 = 'No hay mensajes en esta carpeta';
$text25 = 'Mensaje nuevo';
$text26 = 'Mensajes nuevos';
$text27 = 'Carpetas';
$text28 = 'Preferencias';
$text29 = 'Desconectar';
$text30 = 'Anterior';
$text31 = 'Siguiente';
$text32 = 'Para';
$text33 = 'Adjuntos';
$text34 = 'Responder';
$text35 = 'Redirigir';
$text36 = 'Descargar';
$text37 = 'Imprimir';
$text38 = 'Mover este mensaje a';
$text39 = 'num: ';
$text40 = 'Sin titulo';
$text41 = 'Archivo adjunto';
$text42 = 'Restablecer';
$text43 = 'Enviar';
$text44 = 'Añadir';
$text45 = 'Esperando adjuntos';
$text46 = 'Borrar adjunto';
$text47 = 'Volver';
$text48 = 'Vaciar papelera';
$text49 = 'Mensaje original';
$text50 = 'Nombre carpeta';
$text51 = 'Borrar carpeta';
$text52 = 'Renombrar carpeta';
$text53 = "OK";
$text54 = "Crear nueva carpeta";
$text55 = "Nombre carpeta";
$text56 = "Tema";
$text57 = "Borrar";
$text58 = "No tienes notas";
$text59 = "Total notas";
$text60 = "Añadir nota";
$text61 = "Nombre";
$text62 = "Telefono";
$text63 = "No tienes contatos grabados";
$text64 = "Añadir contactos";
$text65 = "Añadir";
$text66 = "Notas";
$text67 = "Grabar";
$text68 = "Nombre Web";
$text69 = "URL web";
$text70 = "No tienes favoritos grabados";
$text71 = "Añadir favorito";
$text72 = "Por favor, edita global.inc para seleccionar el tipo de base de datos";
$text73 = "Base de datos incorrecta. valores posibles : msql, mysql, postgresql, sybase, mssql";
$text74 = "Idioma incorrecto. valores posibles : turkce, english";
$text75 = "No se puede conectar a la base de datos. Verifica en includes/global.inc la opcion database.";
$text76 = "Acerca de Postaci";
$text77 = "Autores";
$text78 = "Patrocinado por";
$text79 = "Este programa necesita que las cookies esten activadas. Por favor, activa las cookies en tu navegador.";
$text80 = "Hay un error en includes/global.inc : opcion default_protocol. Corrije el error e intentalo de nuevo";
$text81 = "Control de spam";
$text82 = "Bienvenido a Postaci";
$text83 = "Bloqueados";
$text84 = "Postaci es un programa gratis bajo licencia GPL. Para ver mas sobre programas gratis, pulsa aqui <a href='http://www.gnu.org' target='newwindow'>gnu.org</a>";
$text85 = "Borrar";
$text86 = "Añadir a la agenda";
$text87 = "Añadir email a la lista de SPAM";
$text88 = "Cuerpo de mensaje vacio";
$text89 = "El buzon que intentas acceder no existe. Intentalo de nuevo, si el problema persiste contacta con el administrador.";
$text90 = "Has excedido la el espacio permitido de 2 MB o ha ocurrido un error inexperado.";
$text91 = "Problema con el servidor SMTP. Por favor, contacta con el administrador.";
$text92 = "Error : Ya existe una carpeta con el mismo nombre o el buzon no esta vacio.";
$text93 = "Error : El nombre de la carpeta no puede estar en blanco!!!";
$text94 = "Error : La carpeta no esta vacia.";
$text95 = "Error : Ya existe una carpeta con el mismo nombre.";
$text96 = "Usuario añadido a la agenda satisfactoriamente.";
$text97 = "Spammer e-mail";
$text98 = "Fecha añadida a la lista";
$text99 = "Lista vacia";
$text100 = "Tu nombre y apellido";
$text101 = "Tu firma";
$text102 = "Direccion de email invalido, por favor intentalo de nuevo.";
$text103 = "Email Limpio";
$text104 = "Ver";
$text105 = "mensajes por pagina.";
$text106 = "Haz un clic sobre una direccion para agregar al campo seleccionado.";
$text107 = "Permita";
$text108 = "No hay nada para corrigir.";
$text109 = "Cheque de Deletreo";
$text110 = "Texto Original (errores potenciales en <b>negrilla</b>):";
$text111 = "Correcciones";
$text112 = "Corregir";
$text113 = "Reajuste";
$text114 = "Continuar";
$text115 = "No hay errores.";

?>
