<?
/*
   File name         : italiano.inc
   Version           : 1.1.1
   Last Modified By  : Giovanni Panozzo
   e-mail            : giodev@panozzo.it
   Purpose           : Italian localization support for Postaci Webmail.
   Last modified     : 8 Oct 2000
*/

$lang_id = 5;
$lang = "Italiano";
$charset = "iso-8859-1";
$spell_language = "it";

/*************************************************/
/*                  User Panel                   */
/*************************************************/

// Please enter your username and password
$text1 = "Inserire il nome utente e la password.";

// User Name
$text2 = "Utente";

// User Password
$text3 = "Password";

// Log In
$text4 = "Entra";

// Invalid username or password. Try Again
$text5 = "Nome utente o passwrod non validi. Riprova";

// Inbox
$text6 = "Controlla posta";

// Outbox
$text7 = "Posta inviata";

// Trash
$text8 = "Posta eliminata";

// Unknown Error!
$text9 = "Errore sconosciuto!";

// select all
$text10 = "Seleziona tutti";

// deselect all
$text11 = "Deseleziona tutti";

// From
$text12 = "Da";

// Subject
$text13 = "Oggetto";

// Date
$text14 = "Data";

// Size
$text15 = "Dimensione";

// Move Selected Messages To
$text16 = "Sposta messaggio selezionato in";

// Nothing to write here.... Just used for Turkish version
$text17 = " ";

// OK
$text18 = "OK";

// Total Message Count
$text19 = "Numero totale di messaggi";

// e-mail
$text20 = "e-mail";

// notebook
$text21 = "notes";

// address book
$text22 = "rubrica";

// Favorites
$text23 = "preferiti";

// No Messages In This Folder
$text24 = "Nessun messaggio in questa cartella";

// New Message
$text25 = "Nuovo messaggio";

// Check New Mail
$text26 = "Posta in arrivo";

// Folders
$text27 = "Cartelle";

// Preferences
$text28 = "Preferenze";

// Exit
$text29 = "Esci";

// previous message
$text30 = "messaggio precedente";

// next message
$text31 = "messaggio successivo";

// To
$text32 = "A";

// Attachments
$text33 = "Allegati";

// Reply Message
$text34 = "Rispondi al messaggio";

// Forward Message
$text35 = "Inoltra messaggio";

// Save Message
$text36 = "Salva messaggio";

// Print Message
$text37 = "Stampa messaggio";

// Move This Message To
$text38 = "Muovi messaggio in";

// Message No :
$text39 = "Messaggio nr.: ";

// No Subject
$text40 = "Senza oggetto";

// Attach File
$text41 = "Allega file";

// Reset
$text42 = "Reset";	// Where is it used ?

// Send Message
$text43 = "Invia messaggio";

// Add To List
$text44 = "Aggiungi alla lista";

// Waiting Attachments
$text45 = "Attendo allegati";

// Delete Attachment
$text46 = "Elimina allegato";

// Go Back
$text47 = "Indietro";

// Empty Trash
$text48 = "Svuota cartella posta eliminata";

// Original Message
$text49 = "Messaggio originale";

// Folder Name
$text50 = "Nome cartella";

// Delete Folder
$text51 = "Elimina cartella";

// Rename Folder
$text52 = "Rinomina cartella";

// OK
$text53 = "OK";

// Create New Folder
$text54 = "Crea nuova cartella";

// New Folder Name
$text55 = "Nome della nuova cartella";

// Topic
$text56 = "Oggetto";

// Delete
$text57 = "Elimina";

// You Have No Notes
$text58 = "Non ci sono note";

// Total Note Count
$text59 = "Numero totale di note";

// Add Note
$text60 = "Aggiungi nota";

// Name
$text61 = "Nome";

// Telephone Number
$text62 = "Numero di telefono";

// You Have No Cantacts Recorded
$text63 = "Non hai contatti memorizzati";

// Add New Contact
$text64 = "Aggiungi nuovo contatto";

// Add
$text65 = "Aggiungi";

// Notes
$text66 = "Note";

// Save
$text67 = "Salva";

// Site Title
$text68 = "Titolo del sito";

// Site URL
$text69 = "Indirizzo del sito";

// You Have No Bookmarks Recorded
$text70 = "Non ci sono elementi in preferiti";

// Add New Site
$text71 = "Aggiungi nuovo sito";

// Please edit global.inc to select the database type
$text72 = "Dovresti modificare global.inc per selezionare il tipo di database.";

// Invalid database selection. Valid Values : msql, mysql, postgresql, sybase, mssql
$text73 = "Database non valido. Valori validi : msql, mysql, postgresql, sybase, mssql";

// Invalid language selection. Valid values : turkce, english
$text74 = "Lingua non valida. Valori validi : turkce, english";

// Can not connect to database.
$text75 = "Non posso connettermi al database. Controlla global.inc.";

//About Postaci
$text76 = "Info su Postaci";

// Authors
$text77 = "Autori";

// Sponsered By
$text78 = "Sponsorizzato da";

// This software requires that cookies are enabled. Please enable cookies on your browser setting or check if you are behind a firewall or proxy that doesn" t let cookies. Don" t worry, it is a simple unique ID we want to transfer.";
$text79 = "Questo software richiede che i cookies siano abilitati. Dovresti abilitare i cookies nel tuo browser oppure controllare se sei dietro un firewall o proxy che non lascia passare i cookies.";	// i have removed the last sentence...

// You have an error in includes/global.inc : default_protocol setting. Correct the mistake and try again
$text80 = "Errore in includes/global.inc : default_protocol. Correggi e riprova.";

// Spam Control
$text81 = "Controllo spam";	// ???

// Welcome to Postaci
$text82 = "Benvenuto in Postaci";

// Block Senders
$text83 = "Blocca mittenti";

// Postaci is a free software which is licensed by GPL. See <a href='http://www.gnu.org' target='newwindow'>gnu.org</a> for details.
$text84 = "Postaci è un software free ed è licenziato secondo le regole dell GPL. Vedi <a href='http://www.gnu.org' target='newwindow'>gnu.org</a> per i dettagli.";

// Delete Message
$text85 = "Elimina messaggio";

// Add sender to addressbook
$text86 = "Aggiungi mittente alla rubrica";

// Add sender to spam list
$text87 = "Aggiungi mittente alla spam list";

// Message body empty
$text88 = "Il corpo del messaggio è vuoto";

// the mailbox does not exist. Please log again or the problem exists again contact your system administrator.
$text89 = "Il mailbox non esiste. Per favore ritenta l'accesso. Se il problema persiste, contatta il tuo amministratore di sistema.";

// You have exceeded 2 MB file quota.
$text90 = "Hai superato il limite di 2MB.";

// Problem with the SMTP host. Please contact the system administrator.
$text91 = "Problemi con il server SMTP. Per favore contatta l'amministratore di sistema.";

// Error : There is a folder with the same name exists or mailbox not empty.
$text92 = "Errore : c'è una cartella con lo stesso nome oppure la cartella non è vuota."; // this

// Error : Error : Folder name cannot be empty!!!
$text93 = "Errore : Il nome della cartella non può essere vuoto !!!";

// Error : Folder is not empty.
$text94 = "Errore: La cartella non è vuota.";

// Error : Error : A folder with the same name exists.
$text95 = "Errore : Esiste già una cartella con lo stesso nome.";

// User added to the adressbook.
$text96 = "Utente aggiunto alla rubrica.";

// Spammer e-mail
$text97 = "Indirizzo dello spammer";

// Date added to list
$text98 = "Data di aggiunta alla lista";

// Nobody in the list
$text99 = "Nessuno nella lista";

// Your Name and Surname
$text100 = "Il tuo nome e cognome";

// Your Signature
$text101 = "La tua firma";

$text102 = "Email address non valido. Prova Ancora.";
$text103 = "Pulisca Il Email";
$text104 = "Esposizione";
$text105 = "messaggi per la pagina.";
$text106 = "Scatti sopra un indirizzo per aggiungere al campo selezionato.";
$text107 = "Permetta";
$text108 = "Ci non è qualche cosa controllare.";
$text109 = "Controllo Di Periodo";
$text110 = "Testo originale (errori potenziali in <b>GRASSETTO</b>):";
$text111 = "Correzioni:";
$text112 = "Corretto";
$text113 = "Risistemazione";
$text114 = "Continui";
$text115 = "Nessun errori.";
$text116 = "Libro Di Indirizzo Espresso Di Prospettiva Dell'Importazione (Virgola Separata Stima La Disposizione)";
$text117 = "L'Importazione Del Libro Di Indirizzo Riusciva!";
$text118 = "L'Importazione Del Libro Di Indirizzo Non riusciva!";
$text119 = "Istruzioni";
$text120 = "Importazione";

?>
