<?
/*
   File name         : portuguese.inc
   Version           : 1.1.1
   Last Modified By  : Rui Lopes, Jorge Varejao, Jose Rufino
   e-mail            : rdc@bcd.pt
   Purpose           : Portuguese localization support for Postaci Webmail.
   Last modified     : 03 Nov 2000
*/

$lang_id = 6;
$lang = 'Portuguese';
$charset = 'iso-8859-1';
$spell_language = "pt";

/*************************************************/
/*                 User Panel                    */
/*************************************************/

$text1 = 'Introduza o seu nome de Utilizador e a Senha';
$text2 = 'Utilizador';
$text3 = 'Senha';
$text4 = 'Entrar';
$text5 = 'Utilizador ou Senha incorrecta(s). Tente novamente!';
$text6 = 'INBOX';
$text7 = 'Sent Items';
$text8 = 'Drafts';
$text9 = 'Erro desconhecido!';
$text10 = 'Seleccionar tudo';
$text11 = 'Limpar tudo';
$text12 = 'De';
$text13 = 'Assunto';
$text14 = 'Data';
$text15 = 'Tamanho';
$text16 = 'Mover mensagens para';
$text17 = '  ';
$text18 = 'OK';
$text19 = 'Total de mensagens';
$text20 = 'e-mail';
$text21 = 'notas';
$text22 = 'endere&ccedil;os';
$text23 = 'favoritos';
$text24 = 'N&atilde;o existem mensagens nesta pasta';
$text25 = 'Nova mensagem';
$text26 = 'Ler correio';
$text27 = 'Pastas';
$text28 = 'Op&ccedil;&otilde;es';
$text29 = 'Sair';
$text30 = 'Mensagem anterior';
$text31 = 'Mensagem seguinte';
$text32 = 'Para';
$text33 = 'Anexar';
$text34 = 'Responder';
$text35 = 'Reencaminhar';
$text36 = 'Guardar';
$text37 = 'Imprimir';
$text38 = 'Mover para';
$text39 = 'Mensagem No: ';
$text40 = 'Sem assunto';
$text41 = 'Anexar ficheiro';
$text42 = 'Reiniciar';
$text43 = 'Enviar';
$text44 = 'Adicionar';
$text45 = 'anexos';
$text46 = 'Eliminar';
$text47 = 'Regressar';
$text48 = 'Limpar reciclagem';
$text49 = 'Mensagem original';
$text50 = 'Nome da Pasta';
$text51 = 'Remover';
$text52 = 'Renomear';
$text53 = "OK";
$text54 = "Criar nova pasta";
$text55 = "Novo nome da pasta";
$text56 = "T&oacute;pico";
$text57 = "Eliminar";
$text58 = "Ainda n&atilde;o existem notas";
$text59 = "N&uacute;mero total de notas";
$text60 = "Adicionar nota";
$text61 = "Nome";
$text62 = "N&uacute;mero de telefone";
$text63 = "Ainda n&atilde;o tem endere&ccedil;os";
$text64 = "Adicionar endere&ccedil;o";
$text65 = "Adicionar";
$text66 = "Notas";
$text67 = "Guardar";
$text68 = "Nome do s&iacute;tio";
$text69 = "URL do s&iacute;tio";
$text70 = "Ainda n&atilde;o tem URLs";
$text71 = "Adicionar s&iacute;tio";
$text72 = "Please edit global.inc to select the database type";
$text73 = "Invalid database selection. Valid values : msql, mysql, postgresql, sybase, mssql";
$text74 = "Invalid language selection. Valid values : turkce, english, deutsch, dutch, italiano, portuguese";
$text75 = "Cannot connect to database. Check includes/global.inc for database settings. ";
$text76 = "Sobre Postaci";
$text77 = "Autores";
$text78 = "patrocinado por";
$text79 = "Este software requere que o seu browser utilize cookies. Por favor active-os no seu browser";
$text80 = "Existe um erro em includes/global.inc : default_protocol. Corrija o erro e tente de novo";
$text81 = "Controlo de Spam";
$text82 = "Benvindo ao Postaci";
$text83 = "Bloquear emissário";
$text84 = "Postaci é software grátis licenciado por GPL. Para saber mais sobre software grátis, vá até <a href='http://www.gnu.org' target='newwindow'>gnu.org</a>";
$text85 = "Apagar Mensagem";
$text86 = "Adicionar à Lista de Contactos";
$text87 = "Adicionar Emissário à lista de SPAM";
$text88 = "Corpo de Mensagem Vazio";
$text89 = "A conta postal que está a tentar aceder não existe. Por favor tente de novo e se o problema persistir contacte o administrador de sistema.";
$text90 = "Voçê excedeu o limite de quota.";
$text91 = "Ocorreu um problema com o servidor de SMTP. Por favor contacte o administrador de sistema.";
$text92 = "Erro : Existe uma pasta com o mesmo nome ou a pasta não está vazia.";
$text93 = "Erro : O nome da pasta não pode ser nulo.";
$text94 = "Erro : A pasta não está vazia.";
$text95 = "Erro : Existe uma pasta com o mesmo nome.";
$text96 = "Utilizador adicionado com sucesso à lista de contactos.";
$text97 = "E-Mail do Spammer";
$text98 = "Data adicionada à lista";
$text99 = "Não foi encontrado ninguém na lista";
$text100 = "Nome e Sobrenome";
$text101 = "Assinatura";
$text102 = "Email address inválido. Tentativa Outra vez.";
$text103 = "Limpe O Email";
$text104 = "Exposição";
$text105 = "mensagens por a página";
$text106 = "Estale sobre um endereço para adicionar ao campo selecionado.";
$text107 = "Permita";
$text108 = "Não há qualquer coisa verificar.";
$text109 = "Verificação De Período";
$text110 = "Texto original (erros potenciais < em b>bold</b >):";
$text111 = "Correções:";
$text112 = "Correto";
$text113 = "Restauração";
$text114 = "Continue";
$text115 = "Nenhuns erros.";
$text116 = "Livro De Endereço Expresso Do Outlook Da Importação (A Vírgula Separada Avalia O Formato)";
$text117 = "A Importação Do Livro De Endereço Era Bem sucedida!";
$text118 = "A Importação Do Livro De Endereço Não era Bem sucedida!";
$text119 = "Instruções";
$text120 = "Importação";
?>
