<?
/*
   File name         : turkce.inc
   Version           : 1.1.1
   Last Modified By  : Umut Gokbayrak
   e-mail            : umut@trlinux.com
   Purpose           : Turkish localization support for Postaci Webmail.
   Last modified     : 31 Oct 2000
*/

$lang_id = 1;
$lang = "Türkçe";
$charset = "iso-8859-9";

/*************************************************/
/*                  User Panel                   */
/*************************************************/

// Please enter your username and password
$text1 = "Kullanýcý Adý ve Þifrenizi Giriniz.";

// User Name
$text2 = "Kullanýcý";

// User Password
$text3 = "Þifre";

// Log In
$text4 = "tamam";

// Invalid username or password. Try Again
$text5 = "Hatalý kullanýcý adý ya da þifre...Tekrar deneyiniz";

// Inbox
$text6 = "Gelen Mesajlar";

// Outbox
$text7 = "Giden Mesajlar";

// Trash
$text8 = "Taslaklar";

// Unknown Error!
$text9 = "Bilinmeyen hata, tekrar deneyiniz";

// select all
$text10 = "tümünü seç";

// deselect all
$text11 = "seçimi kaldýr";

// From
$text12 = "Kimden";

// Subject
$text13 = "Konu";

// Date
$text14 = "Tarih";

// Size
$text15 = "Boyut";

// Move Selected Messages To
$text16 = "Seçili Mesajlarý";

// Nothing to write here.... Just used for Turkish version
$text17 = "dizinine ";

// OK
$text18 = "taþý";

// Total Message Count
$text19 = "Toplam Mesaj Sayýsý";

// e-mail
$text20 = "e-mail";

// not defteri
$text21 = "not defteri";

// adres defteri
$text22 = "adres defteri";

// Favorites
$text23 = "sevdiðim siteler";

// No Messages In This Folder
$text24 = "hiç mesajýnýz yok.";

// New Message
$text25 = "Yeni Mesaj";

// Check Mail
$text26 = "Mail Kontrol Et";

// Folders
$text27 = "Dizinler";

// Preferences
$text28 = "Seçenekler";

// Exit
$text29 = "Çýkýþ";

// previous message
$text30 = "önceki mesaj";

// next message
$text31 = "sýradaki mesaj";

// To
$text32 = "Kime";

// Attachments
$text33 = "Eklentiler";

// Reply Message
$text34 = "Mesajý Cevapla";

// Forward Message
$text35 = "Mesajý Ýlet";

// Save Message
$text36 = "Mesajý Kaydet";

// Print Message
$text37 = "Mesajý Yazdýr";

// Move This Message To
$text38 = "Bu mesajý ";

// Message No :
$text39 = "Mesaj No:";

// No Subject
$text40 = "Baþlýksýz";

// Attach File
$text41 = "Dosya Ekle";

// Reset
$text42 = "Temizle";

// Send Message
$text43 = "Gönder";

// Add To List
$text44 = "Listeye Ekle";

// Waiting Attachments
$text45 = "Beklemedeki Eklentileriniz";

// Delete Attachment
$text46 = "Eklentiyi Sil";

// Go Back
$text47 = "Geri Dön";

// Empty Trash
$text48 = "Çöp Kutusunu Boþalt";

// Original Message
$text49 = "Orijinal Mesaj";

// Folder Name
$text50 = "Dizin Ýsmi";

// Delete Folder
$text51 = "Dizini Sil";

// Rename Folder
$text52 = "Ýsmini Deðiþtir";

// OK
$text53 = "Tamam";

// Create New Folder
$text54 = "Yeni Dizin Yarat";

// New Folder Name
$text55 = "Yeni Dizin Adý:";

// Topic
$text56 = "Not Baþlýðý";

// Delete
$text57 = "Sil";

// You Have No Notes
$text58 = "Hiç Notunuz Yok";

// Total Note Count
$text59 = "Toplam Not Sayýsý";

// Add Note
$text60 = "Not Ekle";

// Name
$text61 = "Ýsim";

// Telephone Number
$text62 = "Telefon No";

// You Have No Cantacts Recorded
$text63 = "Kayýtlý kimse yok";

// Add New Contact
$text64 = "Yeni kiþi ekleme";

// Add
$text65 = "Ekle";

// Notes
$text66 = "Notlar";

// Save
$text67 = "Kaydet";

// Site Title
$text68 = "Site Baþlýðý";

// Site URL
$text69 = "Site Adresi";

// You Have No Bookmarks Recorded
$text70 = "Kayýtlý Adres Yok";

// Add New Site
$text71 = "Yeni Site Ekleme";

// Please edit global.inc to select the database type
$text72 = "Lütfen global.inc dosyasýnda veritabaný seçimi alanýný doldurunuz.";

// Invalid database selection. Valid Values : msql, mysql, postgresql, sybase, mssql
$text73 = "Yanlýþ veritabaný seçimi. Geçerli veritabanlarý : msql, mysql, postgresql, sybase, mssql";

// Invalid language selection. Valid values : turkce, english
$text74 = "Yanlýþ dil seçimi. Geçerli diller : turkce, english";

// Can not connect to database.
$text75 = "Veritabanýna baðlanýlamadý. includes/global.inc dosyasýný veritabaný ayarlarý için kontrol ediniz.";

//About Postaci
$text76 = "Postacý Nedir?";

// Authors
$text77 = "Yazarlar";

// Sponsered By
$text78 = "sponsor firma";

// This software requires that cookies are enabled. Please enable cookies on your browser setting or check if you are behind a firewall or proxy that doesn" t let cookies. Don" t worry, it is a simple unique ID we want to transfer.";
$text79 = "Bu program cookielere gereksinim duymaktadýr. Bu hata mesajý web tarayýnýzýn ayarlarýnda cookielere izin verilmemesi veya arkasýnda bulunduðunuz bir güvenlik duvarý veya proxy yazýlýmýnýn bunlarý filtrelemesi nedeni ile ortaya çýkar. Lütfen, web tarayýcýnýzýn ayarlarýndan cookieleri aktif hale getiriniz ya da sistem yöneticinize baþvurunuz.";

// You have an error in includes/global.inc : default_protocol setting. Correct the mistake and try again
$text80 = "includes/global.inc dosyasý : default_protocol bölümünde hatanýz var. Hatayý düzeltip tekrar deneyiniz.";

// Spam Control
$text81 = "Spam Kontrolü";

// Welcome to Postaci
$text82 = "Postacýya hoþgeldiniz";

// Block Senders
$text83 = "Gönderen(leri) Blokla";

// Postaci is a free software which is licensed by GPL. See <a href='http://www.gnu.org' target='newwindow'>gnu.org</a> for details.
$text84 = "Postacý, GPL lisansý ile daðýtýlan özgür bir yazýlýmdýr. Özgür yazýlým hakkýnda ayrýntýlý bilgi için <a href='http://www.gnu.org' target='newwindow'>gnu.org</a> adresine bakýnýz.";

// Delete Message
$text85 = "Mesajý Sil";

// Add sender to addressbook
$text86 = "Mesajý Göndereni Adres Defterine Ekle";

// Add sender to spam list
$text87 = "Mesajý Göndereni Spam Listesine Ekle";

// Message body empty
$text88 = "Mesaj içeriði boþ...";

// the mailbox does not exist. Please log again or the problem exists again contact your system administrator.
$text89 = "Ulaþmak istediðiniz posta kutusu mevcut deðil. Eðer problem tekrar ederse sistem yöneticinize baþvurunuz.";

// You have exceeded 2 MB file quota.
$text90 = "2 MB dosya kotasýný geçtiniz ya da bir hata oluþtu.";

// Problem with the SMTP host. Please contact the system administrator.
$text91 = "SMTP sunucusu baðlantýsýnda problem var. Lütfen sistem yöneticinize danýþýnýz.";

// Error : There is a folder with the same name exists or mailbox not empty.
$text92 = "Hata : Ayný isimde bir baþka diizn mevcut ya da posta kutunuz boþ deðil.";

// Error : Error : Folder name cannot be empty!!!
$text93 = "Hata : Dizin ismi boþ olamaz!!!";

// Error : Folder is not empty.
$text94 = "Hata : Dizin boþ deðil.";

// Error : Error : A folder with the same name exists.
$text95 = "Hata : Ayný isimde baþka bir dizin mevcut.";

// User added to the adressbook.
$text96 = "Kullanýcý adres defterine eklendi";

// Spammer e-mail
$text97 = "Spam yapan kiþi e-mail";

// Date added to list
$text98 = "Listeye eklenme tarihi";

// Nobody in the list
$text99 = "Listede hiç kimse yok";

// Your Name and Surname
$text100 = "Ýsminiz ve Soyisminiz";

// Your Signature
$text101 = "Ýmzanýz";


$text105 = "haber -de sayfa";
$text106 = "Týkýrtý üstünde an adres yazmak -e doðru eklemek -e doðru belgili tanýmlýk seçme tarla.";
$text107 = "Olanaklý Kýlmak ";
$text108 = "Var hayýr haber.";
$text109 = "Düzeltmek Imlâ";
$text110 = "Orijinal metin ( potansiyel yanlýþlýk <b>içinde cesur</b> ):";
$text111 = "Tashih";
$text112 = "Düzeltmek";
$text113 = "Araþtýrma";
$text114 = "Devam Etmek";
$text115 = "Hayýr yanlýþlýk.";
$text116 = "Ithal etmek görünüm açýk adres rehberi ( virgül ayýrmak deðer oluþum )";
$text117 = "Adres rehberi ithal etmek Was muvaffakiyetli!";
$text118 = "Adres rehberi ithal etmek Was deðil muvaffakiyetli!";
$text119 = "öðretim";
$text120 = "Ithal Etmek";

