<?
/*
   File name         : commonhead.inc
   Version           : 2.0.0
   Last Modified By  : Pete Larsen
   e-mail            : pete@postaciwebmail.org
   Purpose           : Common tags used in all HTML files' head section
   Last modified     : 28 Feb 2005 
*/

  echo "<html>\n";
  echo "<head>\n";
  echo "<title>$title</title>\n";
  echo "<meta http-equiv='Content-Type' content='text/html; charset=$charset'>\n";
  echo "<meta name='author' content='Pete Larsen'>\n";
?>
