<?
/*
   File name         : deutsch.inc
   Version           : 1.1.1
   Last Modified By  : Matthias Voigt
   e-mail            : my-voigt@gmx.de
   Purpose           : German localization support for Postaci Webmail.
   Last modified     : 04 Oct 2000
*/

$lang_id = 3;
$lang = 'Deutsch';
$charset = 'iso-8859-1';
$spell_language = "de";

/*************************************************/
/*                 User Panel                    */
/*************************************************/

$text1 = 'Bitte Benutzername und Passwort eingeben';
$text2 = 'Benutzername';
$text3 = 'Passwort';
$text4 = 'Log In';
$text5 = 'Ungültiger Benutzername, oder Passwort. Versuchen Sie es noch einmal';
$text6 = 'Posteingang';
$text7 = 'Gesendete Nachrichten';
$text8 = 'Entwürfe';
$text9 = 'Unbekannter Fehler!';
$text10 = 'alles auswählen';
$text11 = 'alles abwählen';
$text12 = 'Von';
$text13 = 'Betreff';
$text14 = 'Datum';
$text15 = 'Grösse';
$text16 = 'bewege markierte Nachrichten nach';
$text17 = '  ';
$text18 = 'OK';
$text19 = 'Anzahl aller Nachrichten';
$text20 = 'e-mail';
$text21 = 'Notizbuch';
$text22 = 'Adressbuch';
$text23 = 'Favoriten';
$text24 = 'Keine Nachrichten in diesem Ordner';
$text25 = 'Neue Nachricht';
$text26 = 'Überprüfe auf neue Nachrichten';
$text27 = 'Ordner';
$text28 = 'Einstellungen';
$text29 = 'Log Out';
$text30 = 'vorige Nachricht';
$text31 = 'nächste Nachricht';
$text32 = 'An';
$text33 = 'Attachments';
$text34 = 'Nachricht beantworten';
$text35 = 'Nachricht weiterleiten';
$text36 = 'Nachricht speichern';
$text37 = 'Nachricht drucken';
$text38 = 'Bewege Nachricht nach';
$text39 = 'Nachricht Nr.: ';
$text40 = 'Kein Btreff';
$text41 = 'Datei anhängen';
$text42 = 'zurücksetzen';
$text43 = 'Nachricht senden';
$text44 = 'zur Liste hinzufügen';
$text45 = 'vorhandene Anhänge';
$text46 = 'lösche Anhang';
$text47 = 'gehe zurück';
$text48 = 'Papierkorb leeren';
$text49 = 'Original Nachricht';
$text50 = 'Ordner Name';
$text51 = 'Ordner löschen';
$text52 = 'Ordner umbenennen';
$text53 = "OK";
$text54 = "neuen Ordner erstellen";
$text55 = "neuer Ordner Name";
$text56 = "Topic";
$text57 = "löschen";
$text58 = "Sie haben keine Notizen";
$text59 = "Anzahl der Notizen";
$text60 = "Neue Notiz";
$text61 = "Name";
$text62 = "Telefonnummer";
$text63 = "Sie haben keine Kontakte gespeichert";
$text64 = "Neuen Kontakt anlegen";
$text65 = "hinzufügen";
$text66 = "Notizen";
$text67 = "speichern";
$text68 = "Seiten Titel";
$text69 = "Seiten Adresse";
$text70 = "Sie haben keine Bookmarks gespeichert";
$text71 = "Neue Seite hinzufügen";
$text72 = "Bitte bearbeiten Sie global.inc um den Datenbank Typ zu bestimmen";
$text73 = "Ungültige Datenbank Auswahl: msql, mysql, postgresql, sybase, mssql";
$text74 = "Ungültige Sprachwahl: turkce, english, german";
$text75 = "Keine Verbindung zur Datenbank. Überprüfen Sie Datenbankeinstellung in includes/global.inc .";
$text76 = "ÜberPostaci";
$text77 = "Authoren";
$text78 = "sponsored by";
$text79 = "Diese Software benötigt Cookies. Bitte aktivieren Sie Cookies in Ihrem Browser oder überpfüfen Sie, ob Sie hinter einem firewall or proxy sind, der keine Cookier erlaubt. Keine Angst, wir möchten nur Eine Zahl übertragen.";
$text80 = "Sie haben einen Fehler in includes/global.inc : default_protocol Einstellung. Bitte beheben, und wiederholen";
$text81 = "Spam Kontrolle";
$text82 = "Willkommen bei Postaci";
$text83 = "Block Sender(s)";
$text84 = "Postaci is a free software which is licensed by GPL. To learn more about free software, see <a href='http://www.gnu.org' target='newwindow'>gnu.org</a>";
$text85 = "Nachricht löschen";
$text86 = "Zum Adressbuch hinzufügen";
$text87 = "Absender zur Spamliste hinzufügen";
$text88 = "Nachrichtenkörper ist leer";
$text89 = "Die angeforderte Mailbox existiert nicht. Bitte versuchen Sie es erneut, oder fragen Sie den System Administrator.";
$text90 = "Sie haben mehr als 2 MB Speicheplatz erreicht, oder ein Fehler ist aufgetreten.";
$text91 = "Problem mit dem SMTP Server. Bitte benachrichtigen Sie Ihren System Administrator.";
$text92 = "Fehler : Es existiert ein Ordner mit dem selben Namen oder Ihre mailbox ist nicht leer.";
$text93 = "Fehler : Ordnername kann nicht leer sein.";
$text94 = "Fehler : Ordner ist nicht leer.";
$text95 = "Fehler : Ein Ordner mit dem selben Namen existiert bereits.";
$text96 = "Benutzer wurde erfolgreich im Adressbuch eingetragen.";
$text97 = "Spammer e-mail";
$text98 = "Datum zu Liste hinzugefügt";
$text99 = "Niemand in der Liste vorhanden";
$text100 = "Ihr Name und Vorname";
$text101 = "Ihre Signatur";
$text102 = "Unzulässiges email address. Versuchen Noch einmal.";
$text103 = "Säubern Sie Email";
$text104 = "Anzeige";
$text105 = "email pro Seite";
$text106 = "Klicken Sie an eine Adresse, um hinzuzufügen vorgewählt auffangen.";
$text107 = "Ermöglichen Sie";
$text108 = "Es gibt nicht nichts zu überprüfen.";
$text109 = "Rechtschreibüberprüfung";
$text110 = "Ursprünglicher Text (mögliche Störungen in <b>fettem</b>):";
$text111 = "Korrekturen:";
$text112 = "Korrekt";
$text113 = "Zurückstellen";
$text114 = "Fahren Sie fort";
$text115 = "Keine Störungen.";
$text116 = "Import-Aussicht-Ausdrückliches Adressbuch (Das Getrennte Komma Bewertet Format)";
$text117 = "Adressbuch-Import War Erfolgreich!";
$text118 = "Adressbuch-Import War Nicht Erfolgreich!";
$text119 = "Anweisungen";
$text120 = "Import";

?>
