<?
/*
   File name         : english.inc
   Version           : 1.1.1
   Last Modified By  : Umut Gokbayrak
   e-mail            : umut@trlinux.com
   Purpose           : English localization support for Postaci Webmail.
   Last modified     : 31 Oct 2000
*/

$lang_id = 2;
$lang = 'English';
$charset = 'iso-8859-1';
$spell_language = "en";

/*************************************************/
/*                 User Panel                    */
/*************************************************/

$text1 = 'Please enter your username and password';
$text2 = 'User Name';
$text3 = 'Password';
$text4 = 'Log In';
$text5 = 'Invalid username or password. Try Again';
$text6 = 'INBOX';
$text7 = 'Sent Items';
$text8 = 'Drafts';
$text9 = 'Unknown Error!';
$text10 = 'select all';
$text11 = 'deselect all';
$text12 = 'From';
$text13 = 'Subject';
$text14 = 'Date';
$text15 = 'Size';
$text16 = 'Move Selected Messages To';
$text17 = '  ';
$text18 = 'OK';
$text19 = 'Total Message Count';
$text20 = 'e-mail';
$text21 = 'notebook';
$text22 = 'address book';
$text23 = 'favorites';
$text24 = 'No Messages In This Folder';
$text25 = 'New Message';
$text26 = 'Check New Mail';
$text27 = 'Folders';
$text28 = 'Preferences';
$text29 = 'Log Out';
$text30 = 'previous message';
$text31 = 'next message';
$text32 = 'To';
$text33 = 'Attachments';
$text34 = 'Reply Message';
$text35 = 'Forward Message';
$text36 = 'Save Message';
$text37 = 'Print Message';
$text38 = 'Move This Message To';
$text39 = 'Message No: ';
$text40 = 'No Subject';
$text41 = 'Attach File';
$text42 = 'Reset';
$text43 = 'Send Message';
$text44 = 'Add To List';
$text45 = 'Waiting Attachments';
$text46 = 'Delete Attachment';
$text47 = 'Go Back';
$text48 = 'Empty Trash';
$text49 = 'Original Message';
$text50 = 'Folder Name';
$text51 = 'Delete Folder';
$text52 = 'Rename Folder';
$text53 = "OK";
$text54 = "Create New Folder";
$text55 = "New Folder Name";
$text56 = "Topic";
$text57 = "Delete";
$text58 = "You Have No Notes";
$text59 = "Total Note Count";
$text60 = "Add Note";
$text61 = "Name";
$text62 = "Telephone Number";
$text63 = "You Have No Contacts Recorded";
$text64 = "Add New Contact";
$text65 = "Add";
$text66 = "Notes";
$text67 = "Save";
$text68 = "Site Title";
$text69 = "Site URL";
$text70 = "You Have No Bookmarks Recorded";
$text71 = "Add New Site";
$text72 = "Please edit global.inc to select the database type";
$text73 = "Invalid database selection. Valid values : msql, mysql, postgresql, sybase, mssql";
$text74 = "Invalid language selection. Valid values : turkce, english";
$text75 = "Can not connect to database. Check includes/global.inc for database settings.";
$text76 = "About Postaci";
$text77 = "Authors";
$text78 = "sponsored by";
$text79 = "This software requires that cookies are enabled. Please enable cookies on your browser setting or check if you are behind a firewall or proxy that does not let cookies. Do not worry, it is a simple unique ID we want to transfer.";
$text80 = "You have an error in includes/global.inc : default_protocol setting. Correct the mistake and try again";
$text81 = "Spam Control";
$text82 = "Welcome to Postaci";
$text83 = "Block Sender(s)";
$text84 = "Postaci is a free software which is licensed by GPL. To learn more about free software, see <a href='http://www.gnu.org' target='newwindow'>gnu.org</a>";
$text85 = "Delete Message";
$text86 = "Add to addressbook";
$text87 = "Add Sender To Spam List";
$text88 = "Message body empty";
$text89 = "The mailbox you try to access does not exist. Please try logging in again, if the problem exists contact your system administrator.";
$text90 = "You have exceeded 2 MB file quota or an error has occured.";
$text91 = "Problem with the SMTP host. Please contact the system administrator.";
$text92 = "Error : There exists a folder with the same name or mailbox not empty.";
$text93 = "Error : Folder name cannot be empty!!!";
$text94 = "Error : Folder is not empty.";
$text95 = "Error : A folder with the same name exists.";
$text96 = "User succesfully added to the adressbook.";
$text97 = "Spammer e-mail";
$text98 = "Date added to list";
$text99 = "Nobody in the list";
$text100 = "Your Name and Surname";
$text101 = "Your Signature";
$text102 = "Invalid email address. Try Again.";
$text103 = "Clean Email";
$text104 = "Display";
$text105 = "emails per page.";
$text106 = "Click on an address to add to the selected field.";
$text107 = "Enable";
$text108 = "There isn't anything to check.";
$text109 = "Spell Check";
$text110 = "Original Text (potential errors in <b>bold</b>):";
$text111 = "Corrections:";
$text112 = "Correct";
$text113 = "Reset";
$text114 = "Continue";
$text115 = "No errors.";
$text116 = "Import Outlook Express Address Book (Comma Separated Values Format)";
$text117 = "Address Book Import Was Successful!";
$text118 = "Address Book Import Was Not Successful!";
$text119 = "Instructions";
$text120 = "Import";

?>
