<?
/*
   File name         : francais.inc
   Version           : 1.1.1
   Last Modified By  : Julien Chauveau
   e-mail            : julien@net-concept.fr
   Purpose           : French localization support for Postaci Webmail.
   Last modified     : 2 Nov 2000
*/

$lang_id = 7;
$lang = 'Français';
$charset = 'iso-8859-1';
$spell_language = "fr";

/*************************************************/
/*                 User Panel                    */
/*************************************************/

// Please enter your username and password
$text1 = 'Please enter your username and password';

// Username
$text2 = "Nom d'utilisateur";

// Password
$text3 = 'Mot de passe';

// Log In
$text4 = 'Connexion';

// Invalid username or password. Try Again
$text5 = 'Votre identification a &eacute;chou&eacute;e. Veuillez recommencer';

// INBOX 
$text6 = 'Courrier entrant';

// Sent Items
$text7 = 'Courrier envoy&eacute;';

// Drafts
$text8 = 'Brouillon';

// Unknown Error!
$text9 = 'Erreur inconnue !';

// select all
$text10 = 'tout s&eacute;lectionner';

// deselect all
$text11 = 'tout d&eacute;s&eacute;lectionner';

// From
$text12 = 'De';

// Subject
$text13 = 'Sujet';

// Date
$text14 = 'Date';

// Size
$text15 = 'Taille';

// Move Selected Messages To
$text16 = 'D&eacute;placer les messages s&eacute;lectionnn&eacute;s vers';

//   
$text17 = '  ';

// OK
$text18 = 'OK';

// Total Message Count
$text19 = 'Nombre de message';

// e-mail
$text20 = 'e-mail';

// notebook
$text21 = 'notes';

// adressbook
$text22 = "carnet d'adresses";

// favorites
$text23 = 'signets';

// No Messages In This Folder
$text24 = 'Aucun message dans ce classeur';

// New Message
$text25 = 'Nouveau message';

// Check New Mail
$text26 = 'V&eacute;rifier le courrier';

// Folders
$text27 = 'Classeurs';

// Preferences
$text28 = 'Pr&eacute;f&eacute;rences';

// Log Out
$text29 = 'D&eacute;connexion';

// previous message
$text30 = 'message pr&eacute;c&eacute;dent';

// next message
$text31 = 'message suivant';

// To
$text32 = 'A';

// Attachments
$text33 = 'Fichiers joints';

// Reply Message
$text34 = 'R&eacute;pondre';

// Forward Message
$text35 = 'Faire suivre';

// 'Save Message
$text36 = 'T&eacute;l&eacute;charger';

// Print Message
$text37 = 'Imprimer';

// Move This Message To
$text38 = 'D&eacute;placer ce message vers';

// Message No: 
$text39 = 'Message n° ';

// No Subject
$text40 = 'Pas de sujet';

// Attach File
$text41 = 'Joindre un fichier';

// Reset
$text42 = 'Reset';

// Send Message
$text43 = 'Envoyer';

// Add To List
$text44 = 'Ajouter ce fichier';

// Waiting Attachments
$text45 = 'Fichiers en attente';

// Delete Attachment
$text46 = 'Effacer';

// Go Back
$text47 = 'Retour';

// Empty Trash
$text48 = 'La corbeille est vide';

// Original Message
$text49 = 'Message original';

// Folder Name
$text50 = 'Nom du classeur';

// Delete Folder
$text51 = 'Effacer';

// Rename Folder
$text52 = 'Renommer';

// OK
$text53 = "OK";

// Create New Folder
$text54 = "Cr&eacute;er un nouveau classeur";

// New Folder Name
$text55 = "Nouveau nom";

// Topic
$text56 = "Sujet";

// Delete
$text57 = "Effacer";

// You Have No Notes
$text58 = "Vous n'avez aucune note";

// Total Note Count
$text59 = "Nombre de note";

// Add Note
$text60 = "Ajouter une note";

// Name
$text61 = "Nom";

// Telephone Number
$text62 = "Num&eacute;ro de t&eacute;l&eacute;phone";

// You Have No Cantacts Recorded
$text63 = "Votre carnet d'adresse est vide";

// Add New Contact
$text64 = "Ajouter un contact";

// Add
$text65 = "Ajouter";

// Notes
$text66 = "Notes";

// Save
$text67 = "Enregister";

// Site Title
$text68 = "Nom du site";

// Site URL
$text69 = "URL du site";

// You Have No Bookmarks Recorded
$text70 = "Vous n'avez aucun signet";

// Add New Site
$text71 = "Ajouter un signet";

// Please edit global.inc to select the database type
$text72 = "Editez global.inc pour configurer votre base de donn&eacute;es";

// Invalid database selection. Valid values : msql, mysql, postgresql, sybase, mssql
$text73 = "Base de donn&eacute;es invalide. Les valeurs possibles sont : msql, mysql, postgresql, sybase, mssql";

// Invalid language selection. Valid values : turkce, english
$text74 = "Choix de langue invalide. Les valeurs possibles sont : turkce, english";

// Can not connect to database. Check includes/global.inc for database settings.
$text75 = "Connexion &agrave; la base de donn&eacute;es impossible. V&eacute;rifiez le fichier includes/global.inc.";

// About Postaci
$text76 = "A propos de Postaci";

// Authors
$text77 = "Auteurs";

// sponsored by
$text78 = "avec le soutien de";

// This software requires that cookies are enabled. Please enable cookies on your browser setting or check if you are behind a firewall or proxy that does not let cookies. Do not worry, it is a simple unique ID we want to transfer.
$text79 = "Ce programme n&eacute;cessite l'activation des cookies. Veuillez activer la gestion des cookies dans les pr&eacute;f&eacute;rences de votre navigateur.";

// You have an error in includes/global.inc : default_protocol setting. Correct the mistake and try again
$text80 = "Le fichier includes/global.inc est incorrect : veuillez v&eacute;rifier le param&egrave;tre 'default_protocol'.";

// Spam Control
$text81 = "Contr&ocirc;le du spam";

// Welcome to Postaci
$text82 = "Bienvenue sur Postaci";

// Block Sender(s)
$text83 = "Block Sender(s)";

// Postaci is a free software which is licensed by GPL. To learn more about free software, see <a href='http://www.gnu.org' target='newwindow'>gnu.org</a>
$text84 = "Postaci est un logiciel libre sous licence GPL. Pour obtenir plus d'informations sur les logiciels libres, visitez le site <a href='http://www.gnu.org' target='newwindow'>gnu.org</a>";

// Delete Message
$text85 = "Effacer";

// Add to addressbook
$text86 = "Ajouter au carnet d'adresses";

// Add Sender To Spam List
$text87 = "Ajouter ce contact dans la liste de spam";

// Message body empty
$text88 = "Ce message ne contient aucune donn&eacute;e";

// The mailbox you try to access does not exist. Please try logging in again, if the problem exists contact your system administrator.
$text89 = "Ce compte n'est pas valide. Essayez de vous r&eacute;identifier, si le probl&egrave;me persiste, contactez votre administrateur syst&egrave;me..";

// You have exceeded 2 MB file quota or an error have occured.
$text90 = "Soit la taille de votre fichier est sup&eacute;rieure &agrave; 2 Mo, soit le programme est mal configur&eacute;.";

// Problem with the SMTP host. Please contact the system administrator.
$text91 = "Il y a un probl&egrave;me avec le serveur SMTP. Veuillez contacter votre administrateur syst&egrave;me.";

// Error : There exists a folder with the same name or mailbox not empty.
$text92 = "Erreur : Il existe d&eacute;j&agrave; un classeur poss&eacute;dant ce nom.";

// Error : Folder name cannot be empty!!!
$text93 = "Erreur : Vous devez donner un nom au classeur !!!";

// Error : Folder is not empty.
$text94 = "Erreur : Ce classeur n'est pas vide.";

// Error : A folder with the same name exists.
$text95 = "Erreur : Il existe d&eacute;j&agrave; un classeur poss&eacute;dant ce nom.";

// User succesfully added to the adressbook.
$text96 = "Ce contact &agrave; bien &eacute;t&eacute; ajout&eacute; au carnet d'addresses";

// Spammer e-mail
$text97 = "E-mail de spam";

// Date added to list
$text98 = "Cette date &agrave; &eacute;t&eacute; ajout&eacute;e &agrave; la liste.";

// Nobody in the list
$text99 = "La liste est vide";

// Your Name and Surname
$text100 = "Vos nom et pr&eacute;nom";

// Your Signature
$text101 = "Votre signature";

$text102 = "Email address inadmissible. Essai Encore.";
$text103 = "Nettoyez L'Email";
$text104 = "Affichage";
$text105 = "messages par la page.";
$text106 = "Cliquez sur une adresse pour s'ajouter au champ choisi.";
$text107 = "Permettez";
$text108 = "Il n'y a pas quelque chose vérifier.";
$text109 = "Contrôle De Charme";
$text110 = "Texte original (erreurs potentielles dans <b>'bold'</b>) :";
$text111 = "Corrections:";
$text112 = "Correct";
$text113 = "Remise";
$text114 = "Continuez";
$text115 = "Aucunes erreurs.";
$text116 = "Carnet d'adresses Exprès De Perspectives D'Importation (La Virgule Séparée Évalue Le Format)";
$text117 = "L'Importation De Carnet d'adresses Était Réussie !";
$text118 = "L'Importation De Carnet d'adresses N'était pas Réussie !";
$text119 = "Instructions";
$text120 = "Importation";

?>
