<?
/*
   File name         : norsk.inc
   Version           : 1.1.1
   Last Modified By  : Åge Bårdsen 
   e-mail            : aageb@izeman.com
   Purpose           : Norwegian localization support for Postaci Webmail.
   Last modified     : 3 Nov. 2000
*/

$lang_id = 8;
$lang = 'Norsk';
$charset = 'iso-8859-1';
$spell_language = "nn";

/*************************************************/
/*                 User Panel                    */
/*************************************************/

$text1 = 'Vennligst skriv inn ditt brukernavn og passord';
$text2 = 'Brukernavn';
$text3 = 'Passord';
$text4 = 'Logg inn';
$text5 = 'Feil brukernavn eller passord. Prøv igjen';
$text6 = 'INNBOKS';
$text7 = 'Sendte elementer';
$text8 = 'Kladder';
$text9 = 'Ukjent feil!';
$text10 = 'velg alle';
$text11 = 'ommarker alle';
$text12 = 'Fra';
$text13 = 'Emne';
$text14 = 'Dato';
$text15 = 'Størrelse';
$text16 = 'Flytt markerte beskjeder Til';
$text17 = '  ';
$text18 = 'OK';
$text19 = 'Total beskjed indeks';
$text20 = 'e-post';
$text21 = 'notatblokk';
$text22 = 'adressebok';
$text23 = 'favoritter';
$text24 = 'Ingen beskjeder i denne mappen';
$text25 = 'Ny Melding';
$text26 = 'Se etter ny post';
$text27 = 'Mapper';
$text28 = 'Foretrekninger';
$text29 = 'Logg Ut';
$text30 = 'forrige melding';
$text31 = 'neste melding';
$text32 = 'Til';
$text33 = 'Vedlegg';
$text34 = 'Svar til melding';
$text35 = 'Videresend melding';
$text36 = 'Lagre melding';
$text37 = 'Utskrift av melding';
$text38 = 'Flytt denne beskjeden til';
$text39 = 'Melding Nr: ';
$text40 = 'Ingen emne';
$text41 = 'Vedlegg Fil';
$text42 = 'Oppfrisk';
$text43 = 'Send Melding';
$text44 = 'Legg til listen';
$text45 = 'Ventende vedlegg';
$text46 = 'Slett vedlegg';
$text47 = 'Gå Tilbake';
$text48 = 'Tøm papirkurven';
$text49 = 'Orginal Melding';
$text50 = 'Mappe Navn';
$text51 = 'Slett Mappe';
$text52 = 'Endre Mappenavn';
$text53 = "OK";
$text54 = "Lag ny mappe";
$text55 = "Navnet på ny mappe";
$text56 = "Emne";
$text57 = "Slett";
$text58 = "Du har ingen notater";
$text59 = "Total notater";
$text60 = "Legg til notat";
$text61 = "Navn";
$text62 = "Telefon Nummer";
$text63 = "Du har ikke lagret noen kontakter";
$text64 = "Legg til ny kontakt";
$text65 = "Legg til";
$text66 = "Notater";
$text67 = "Lagre";
$text68 = "wevsteds tittel";
$text69 = "wevsteds URL";
$text70 = "Du har ingen favoritter lagret";
$text71 = "Leggtil ny wevsted";
$text72 = "Vennligst rediger global.inc for å velge database type";
$text73 = "Ukjent database valg. Korrekte verdier : msql, mysql, postgresql, sybase, mssql";
$text74 = "Ikke tilgjengelig språk valg: Tilgjengelige : tykisk, engelsk";
$text75 = "Kan ikke koble til database. Sjekk includes/global.inc for database innstillinger.";
$text76 = "Om Postaci";
$text77 = "Forfattere";
$text78 = "Sponset av";
$text79 = "Dette programmet trenger en funksjon kalt cookies i din webleser, sett støtte for cookies i din webleser og prøv igjen";
$text80 = "Du har en feil i includes/global.inc, standard protokoll innstilling. Utarbeid feilen og prøv igjen";
$text81 = "Spam kontroll";
$text82 = "Velkommen til Postaci";
$text83 = "Blokker Avsender(e)";
$text84 = "Postaci er gratis programvare lisensiert av GPL. For å lære mer om gratis programvare, se <a href='http://www.gnu.org' target='newwindow'>gnu.org";
$text85 = "Slett Melding";
$text86 = "Legg til adressebok";
$text87 = "Legg avsender Til Spam Liste";
$text88 = "Beskjeden er tom!";
$text89 = "Postboksen du prøver å aksessere finnes ikke. Vennligst prøv å logg på igjen, hvis problemet fortsetter kontakt systemansvarlig.";
$text90 = "Du har brukt kapasiten det er for å lagre! (2mb) (Eller en feil kan ha oppstått)";
$text91 = "Problemer med å sende epost. Vennligst kontakt systemansvarlig.";
$text92 = "Feil : Det finnes en mappe med det samme navnet, eller postboksen er ikke tom";
$text93 = "Feil : En mappe må ha et navn!";
$text94 = "Feil : Mappen er ikke tom!";
$text95 = "Feil : En mappe med det samme navnet finnes fra før!";
$text96 = "Bruker lagt til gruppen med suksess";
$text97 = "Spammer e-post";
$text98 = "Dato lagt til i listen";
$text99 = "Ingen i listen";
$text100 = "Ditt navn og mellomnavn";
$text101 = "Din signatur";
$text102 = "Invalid email henvende seg. Prøve Atter.";
$text103 = "Feilfri Email";
$text104 = "Utfoldelse";
$text105 = "beskjeder per side";
$text106 = "Falle i staver opp på en rette til legge til det valgt åker.";
$text107 = "sette i stand";
$text108 = "Der er ikke alt å sjekk.";
$text109 = "Stave Sjekk";
$text110 = "Original Tekst ( muligheter feilene inne <b>dristig</b> ):";
$text111 = "Korrigeringen:";
$text112 = "Korrekt";
$text113 = "Restarte";
$text114 = "Fortsette";
$text115 = "Nei feilene.";
$text116 = "Import Utsikt Ekspres Adresseboken ( kommaet Adskilt Verdier Formatter )";
$text117 = "Adresseboken Import Var Heldig!";
$text118 = "Adresseboken Import Var Ikke Heldig!";
$text119 = "Instruksjoner";
$text120 = "Importen";
?>
