<?
/*
   File name         : polish.inc
   Version           : 1.1.1
   Last Modified By  : Maciej Wilczynski
   e-mail            : rasta@hiphop.hifi.pl
   Purpose           : Polish localization support for Postaci Webmail.
   Last modified     : 04 Nov 2000
*/

$lang_id = 10;
$lang = 'Polish';
$charset = 'iso-8859-2';

/*************************************************/
/*                 User Panel                    */
/*************************************************/

$text1 = 'Proszê podaæ nazwê konta oraz has³o';
$text2 = 'U¿ytkownik';
$text3 = 'Has³o';
$text4 = 'Logowanie';
$text5 = 'Nieprawid³owa nazwa konta lub has³o. Spróbuj ponownie';
$text6 = 'Odebrane';
$text7 = 'Wys³ane';
$text8 = 'Szkice';
$text9 = 'Nieznany B³±d!';
$text10 = 'zaznacz wszystko';
$text11 = 'odznacz wszystko';
$text12 = 'Od';
$text13 = 'Temat';
$text14 = 'Data';
$text15 = 'Wielko¶æ';
$text16 = 'Przenie¶ wiadomo¶ci do';
$text17 = '  ';
$text18 = 'OK';
$text19 = 'Ilo¶æ wiadomo¶ci';
$text20 = 'e-mail';
$text21 = 'notatnik';
$text22 = 'adresy';
$text23 = 'ulubione';
$text24 = 'Brak wiadomo¶ci';
$text25 = 'Nowa wiadomo¶æ';
$text26 = 'Odbierz pocztê';
$text27 = 'Foldery';
$text28 = 'Ustawienia';
$text29 = 'Wyjdz';
$text30 = 'poprzednia wiadomo¶æ';
$text31 = 'nastêpna wiadomo¶æ';
$text32 = 'Dla';
$text33 = 'Za³±czniki';
$text34 = 'Odpowiedz';
$text35 = 'Prze¶lij dalej';
$text36 = 'Zapisz Wiadomo¶æ';
$text37 = 'Drukuj';
$text38 = 'Przenie¶ do';
$text39 = 'Numer wiadomo¶ci: ';
$text40 = 'Brak Tematu';
$text41 = 'Za³±cznik';
$text42 = 'Reset';
$text43 = 'Wy¶lij';
$text44 = 'Dodaj do listy';
$text45 = 'Oczekuj±ce za³±czniki';
$text46 = 'Usuñ Za³±cznik';
$text47 = 'Powrót';
$text48 = 'Usuñ zawarto¶ kosza';
$text49 = 'Orginalna tre¶æ';
$text50 = 'Nazwa Folderu';
$text51 = 'Usuñ Folder';
$text52 = 'Zmieñ Nazwê';
$text53 = "OK";
$text54 = "Dodaj nowy folder";
$text55 = "Nazwa nowego folderu";
$text56 = "Temat";
$text57 = "Usuñ";
$text58 = "Brak notatek";
$text59 = "Ilo¶æ notatek";
$text60 = "Dodaj Notatkê";
$text61 = "Nazwisko";
$text62 = "Numer telefonu";
$text63 = "Brak kontaktów";
$text64 = "Dodaj nowy kontakt";
$text65 = "Dodaj";
$text66 = "Notatka";
$text67 = "Zapisz";
$text68 = "Nazwa strony";
$text69 = "Adres URL";
$text70 = "Brak zak³adek";
$text71 = "Dodaj now± zak³adkê";
$text72 = "Proszê zdefiniowaæ typ bazy danych w pliku global.inc";
$text73 = "Wybrany nieprawid³owy typ bazy danych. Poprawne warto¶ci : msql, mysql, postgresql, sybase, mssql";
$text74 = "Invalid language selection. Valid values : turkce, english, polish";
$text75 = "Brak po³±czenia z baz± danych. Sprawdz uwstawienia konfiguracyjne.";
$text76 = "O Postaci";
$text77 = "Autorzy";
$text78 = "sponsorowane przez";
           
$text79 = "Ten program wymaga aktywnych cookies. Proszê w³±czyæ je w opcjach przegl±darki, je¶li jeste¶ za firewalem lub proxy nie martw siê wysylamy z cookie tylko numer ID.";
$text80 = "Wykryto b³±d w pliku includes/global.inc : sprawdz default_protocol. Popraw ten b³±d i spróbuj ponownie";
$text81 = "Kontrola Spamu";
$text82 = "Witamy w Postaci";
$text83 = "Block Sender(s)";
$text84 = "Postaci jest darmowym programem opartym na licencji GPL, je¶li chcesz siê dowiedzieæ wiêcej zobacz <a href='http://www.gnu.org' target='newwindow'>gnu.org</a>";
$text85 = "Usuñ";
$text86 = "Dodaj do adresów";
$text87 = "Dodaj nadawcê do listy spamerów";
$text88 = "Pusta wiadomo¶æ";
$text89 = "Skrzynka nieistnieje. Prosimy spróbowaæ ponownie, je¶li problem bêdzie siê powtarza³ skontaktuj siê z administratorem.";
$text90 = "Przekroczy³e¶ dozwoln± wielko¶æ pliku (2MB), lub wyst±pi³ inny b³±d.";
$text91 = "Problem z hostem SMTP. Prosimy o kontakt z administratorem.";
$text92 = "B³±d : Istnieje ju¿ folder o tej nazwie.";
$text93 = "B³±d : Nazwa folderu nie mo¿e byæ pusta!!!";
$text94 = "B³±d : Folder nie jest pusty.";
$text95 = "B³±d : Istnieje ju¿ folder o tej samej nazwie.";
$text96 = "Prawid³owo doda³em adres do ksiêgi adresowej.";
$text97 = "Spammer e-mail";
$text98 = "Data dodania do listy";
$text99 = "Nikogo na li¶cie";
$text100 = "Twoje imiê i nazwisko";
$text101 = "Twoja sygnatura";
$text102 = "Niewa|ny poczta elektroniczna przemawia. Próbowa Znowu.";
$text103 = "Czysty Poczta elektroniczna";
$text104 = "Wystawa";
$text105 = "wiadomo[ci na stronica";
$text106 = "Trzaska u an przemawia wobec dolicza ten wybrany strefa.";
$text107 = "Umo|liwia";
$text108 = "Tam nie jest co[ wobec sprawdzanie.";
$text109 = "Przeliterowa Sprawdzanie";
$text110 = "Pierwotny Tekst ( potencjalny bBdy w <b>[miaBy</b> ):";
$text111 = "Poprawki:";
$text112 = "Poprawny";
$text113 = "Badanie";
$text114 = "Kontynuowa";
$text115 = "Nie bBdy.";
$text116 = "Importowa Wydatek Wyra|a Ksiga adresowa ( przecinek Oddzielony Warto[ UkBad graficzny )";
$text117 = "Ksiga adresowa Importowa ByB Pomy[lny!";
$text118 = "Ksiga adresowa Importowa ByB Nie Pomy[lny!";
$text119 = "Zalecenia";
$text120 = "Importowa";


?>
